---
- hosts: all
  connection: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml
      tags: ['always']

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mas
      when: mas_installed_apps
      tags: ['mas']
    - role: geerlingguy.dotfiles
      when: configure_dotfiles
      tags: ['dotfiles']

  tasks:
    - include: tasks/ansible-setup.yml

    - include: tasks/macos.yml
      when: configure_macos
      tags: ['macos']

    - include: tasks/apps.yml
      when: configure_apps
      tags: ['apps']

    - include: tasks/dropbox.yml
      when: configure_dropbox
      tags: ['dropbox']

    - include: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - include: tasks/editor_kb.yml
      vars:
        gui_editor:
          - com.sublimetext.3
          - com.apple.dt.Xcode
          - com.googlecode.iterm2
      when: configure_editors
      tags: ['editors']

    - include: tasks/composer.yml
      when: configure_editors
      tags: ['composer']

    - include: tasks/node.yml
      when: configure_node
      tags: ['node']

    - include: tasks/pip.yml
      when: configure_pip
      tags: ['pip']

    - include: tasks/ruby.yml
      when: configure_ruby
      tags: ['ruby']

    - name: Run configured post-provision ansible task files.
      include: "{{ outer_item }}"
      loop_control:
        loop_var: outer_item
      with_fileglob: "{{ post_provision_tasks|default(omit) }}"
